2021-12-07 19:44:50,748 INFO    MainThread:332051 [wandb_setup.py:_flush():71] setting env: {}
2021-12-07 19:44:50,748 INFO    MainThread:332051 [wandb_setup.py:_flush():71] setting login settings: {}
2021-12-07 19:44:50,748 INFO    MainThread:332051 [wandb_init.py:_log_setup():371] Logging user logs to /home/beegass/Documents/Coding/Readable-VAEs/vae-pytorch/wandb/run-20211207_194450-2kypi51v/logs/debug.log
2021-12-07 19:44:50,748 INFO    MainThread:332051 [wandb_init.py:_log_setup():372] Logging internal logs to /home/beegass/Documents/Coding/Readable-VAEs/vae-pytorch/wandb/run-20211207_194450-2kypi51v/logs/debug-internal.log
2021-12-07 19:44:50,749 INFO    MainThread:332051 [wandb_init.py:init():404] calling init triggers
2021-12-07 19:44:50,749 INFO    MainThread:332051 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {}
2021-12-07 19:44:50,749 INFO    MainThread:332051 [wandb_init.py:init():449] starting backend
2021-12-07 19:44:50,749 INFO    MainThread:332051 [backend.py:_multiprocessing_setup():95] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-12-07 19:44:50,758 INFO    MainThread:332051 [backend.py:ensure_launched():199] starting backend process...
2021-12-07 19:44:50,764 INFO    MainThread:332051 [backend.py:ensure_launched():204] started backend process with pid: 332166
2021-12-07 19:44:50,765 INFO    MainThread:332051 [wandb_init.py:init():458] backend started and connected
2021-12-07 19:44:50,766 INFO    MainThread:332051 [wandb_init.py:init():519] updated telemetry
2021-12-07 19:44:50,784 INFO    MainThread:332051 [wandb_init.py:init():549] communicating current version
2021-12-07 19:44:51,644 INFO    MainThread:332051 [wandb_init.py:init():554] got version response 
2021-12-07 19:44:51,644 INFO    MainThread:332051 [wandb_init.py:init():564] communicating run to backend with 30 second timeout
2021-12-07 19:44:52,054 INFO    MainThread:332051 [wandb_init.py:init():592] starting run threads in backend
2021-12-07 19:44:52,087 INFO    MainThread:332051 [wandb_run.py:_console_start():1816] atexit reg
2021-12-07 19:44:52,087 INFO    MainThread:332051 [wandb_run.py:_redirect():1690] redirect: SettingsConsole.REDIRECT
2021-12-07 19:44:52,088 INFO    MainThread:332051 [wandb_run.py:_redirect():1695] Redirecting console.
2021-12-07 19:44:52,089 INFO    MainThread:332051 [wandb_run.py:_redirect():1751] Redirects installed.
2021-12-07 19:44:52,089 INFO    MainThread:332051 [wandb_init.py:init():619] run started, returning control to user process
2021-12-07 20:07:12,945 INFO    MainThread:332051 [wandb_run.py:_atexit_cleanup():1786] got exitcode: 255
2021-12-07 20:07:12,946 INFO    MainThread:332051 [wandb_run.py:_restore():1758] restore
2021-12-07 20:07:15,236 INFO    MainThread:332051 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 756
  total_bytes: 756
}

2021-12-07 20:07:15,689 INFO    MainThread:332051 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 756
  total_bytes: 756
}

2021-12-07 20:07:16,520 INFO    MainThread:332051 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 756
  total_bytes: 10257
}

2021-12-07 20:07:16,623 INFO    MainThread:332051 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 756
  total_bytes: 10257
}

2021-12-07 20:07:16,725 INFO    MainThread:332051 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 756
  total_bytes: 10257
}

2021-12-07 20:07:16,827 INFO    MainThread:332051 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 756
  total_bytes: 10257
}

2021-12-07 20:07:16,930 INFO    MainThread:332051 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 756
  total_bytes: 10257
}

2021-12-07 20:07:17,032 INFO    MainThread:332051 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 756
  total_bytes: 10257
}

